EP3 /config/routes.rb
Rails.application.routes.draw do
  
 
    root 'pages#home'
    resources :movies

    get 'home' => 'pages#home'
    devise_for :users
    get 'users' => 'users#index'
    get 'index' => 'pages#index'
  get 'category' => 'movies#category'

end

EP3 /app/models/movie.rb
class Movie < ActiveRecord::Base
has_many :comentarios
	has_attached_file :image, styles: { large:"500x500>",medium: "300x300>", thumb: "100x100<" }, default_url: "missing.png"
		validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

EP3 /app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
     #  @@adm=false;
end

EP3 /app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

EP3 /app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	protect_from_forgery
	before_action :authenticate_user!, only:[:new,:create,:update,:edit,:destroy]
#The methode above works fine, remember to implement for method vote and for the comments for movies



	def index

				if  (params[:search]!=nil || ( !params[:search])) || (( !params[:search]!=nil) || params[:search])
								@movies = Movie.where("name like '%#{params[:search]}%'")					
							
					else
						@movies = Movie.all 
					end

	end
	

	def new

		@movie = Movie.new
	end
	
	
	def create
		@movie = Movie.new(movie_params)
		
		if @movie.save
			redirect_to @movie
		else
			render 'new'
		end
	end


	def show

		@movie = Movie.find(params[:id])	

	end

	
	def edit
	
		@movie= Movie.find(params[:id])
	
	end

	def category
		@movies = Movie.where(category: params[:category])
	end

	def update

		@movie= Movie.find(params[:id])
	
		if @movie.update_attributes(movie_params)
			redirect_to @movie
		else
			render 'edit'
		end
	
	end

	def destroy

		@movie= Movie.find(params[:id])
	    @movie.destroy

	    redirect_to 'home'

	end
	def movie_params

		params.require(:movie).permit(:name,:description,:director,:year,:category,:image,:nota,:voto,:media)		
	end


end

EP3 /app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def home
  	
  end
end

EP3 /app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
 def index
    @users = User.all
  end

end

EP3 /app/helpers/application_helper.rb
module ApplicationHelper
end

EP3 /app/helpers/movies_helper.rb
module MoviesHelper
def avalia(nota)
		
		@movie.voto + 1

		@movie.media = @movie.nota / @movie.voto
		
	
	
	end	
end

EP3 /app/helpers/pages_helper.rb
module PagesHelper
end

EP3 /app/helpers/users_helper.rb
module UsersHelper
end

EP3 /app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>CineMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="top-nav">
  <div class="navbar-fixed">
    <nav id="main-navbar">
      <%= link_to image_tag("logo.png", alt: "Logo", id: "logo-image"), index_path %>
      <div class="nav-wrapper yellow darken-4 white-text" id="login-buttons">
      <% if user_signed_in? %>
          Logged in as&nbsp;&nbsp;<strong><%= current_user.email %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>                                 
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </nav>
  </div>
  </header>

  <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

EP3 /app/views/movies/edit.html.erb
<div class="row">

			<div class="col s5">

			<div class="container">
			<%= form_for (@movie) do |f| %>
				
				<%= f.label :name , "Nome do filme"%>
				<%= f.text_field :name %>

				<%= f.label :description, "Descrição" %>
				<%= f.text_field :description %>

				<%= f.label :year, "Ano" %>
				<%= f.text_field :year %>

				<%= f.label :director, "Diretor" %>
				<%= f.text_field :director %>

				<%= f.label :category, "Categoria" %>
				<%= f.text_field :category%>

				<a class="waves-effect waves-light btn"><%= f.submit "Editar" 	%></br>
				</a>

				</div>
			</div>


			<div class="col s5">
					<%= form_for @movie, url: movies_path, html: { multipart: true } do |form| %>
					<%= form.file_field :image %>
					<% end %>
			</div>

							
			<% end %>
			</div>

EP3 /app/views/movies/index.html.erb
<head>

	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <div class="fixed-action-btn click-to-toggle" style="top: 55px;right:20;">
    <a class="waves-effect waves-light btn-large yellow darken-4">
      <i class="large material-icons">Explorar</i>
      <i class="large mdi-navigation-menu"></i>
    </a>
    <ul>
      <li><%= link_to "Ação", category_path(category: "Ação"), class: "waves-effect waves-light btn teal darken-4" %></li>
      <li><%= link_to "Animação", category_path(category: "Animação"), class: "waves-effect waves-light btn green" %></li>
      <li><%= link_to "Comédia", category_path(category: "Comédia"), class: "waves-effect waves-light btn yellow darken-1" %></li>
      <li><%= link_to "Drama", category_path(category: "Drama"), class: "waves-effect waves-light btn deep-blue lighten-4" %></li>
      <li><%= link_to "Documentário", category_path(category: "Documentário"), class: "waves-effect waves-light btn teal darken-2" %></li>
      <li><%= link_to "Ficção Científica", category_path(category: "Ficção Científica"), class: "waves-effect waves-light btn grey darken-2" %></li>
      <li><%= link_to "Romance", category_path(category: "Romance"), class: "waves-effect waves-light btn red" %></li>
    </ul>
    </div>
    <div class="container" style="width:40%">
       <%= form_tag(movies_path, :method => :get) do %>

        <%= text_field_tag 'search', nil, placeholdder: 'Enter search ter...'%>
          
          <%= submit_tag "Search" %>
            
        <% end %>
    </div>
</head>
<body>
	<center>
<div class="container">
<% @movies.each do |mov| %>
<div class="row">
<div class="col m5 s5 l5">
			  <div class="card s-deepth-3" style="top:10px; width:130%" >

			      <%= link_to image_tag(mov.image.url, height: '200', width: '200'),mov%>
			    
			   
			    <div class="card-content white-text">
			      <span class="card-title activator grey-text text-darken-4">

			      	<%= mov.name%>
			      	
			      	<i class="material-icons right blue-text">more_vert</i></span>
			   
			    </div>
			    
			    <div class="card-reveal blue-grey darken-1">
			      
			      <span class="card-title white-text "><h5><i class="material-icons center white-text right">close</i></h5></span>

			      <div class="row ">	

					<div class="col s5 white-text">
						  
						  <div class="divider"></div>
							<div class="section">
							<p>	Título: <%= mov.name%>
							</p>
							</div>


						  <div class="divider"></div>

							<div class="section">
							<p>
								Categoria: <%= mov.category%>
							</p>
							</div>

							<div class="divider">Ano</div>

							<div class="section">
							<p>
								Ano: <%= mov.year%>
							</p>
							</div>

							<div class="divider"></div>

							<div class="section">
							<p>
								Diretor: <%= mov.director%>
							</p>
							</div>
						</div>

						<div class="col s5 white-text">
							<div class="divider"></div>
							<div class="section">
							<p>
								Sinopse</br>
								</br>
								<%= mov.description%>
							</p>
							
						</div>


						</div>
			    </div>
			  </div>


	</div>
</div>
</div>
<% end %>
</div>

</center>

</body>

EP3 /app/views/movies/new.html.erb
<div class="row">
	<div class="col s5">
					<div class="container"	>
					<%= form_for (@movie) do |f| %>
						
						<%= f.label :name , "Nome do filme"%>
						<%= f.text_field :name %>

						<%= f.label :description, "Descrição" %>
						<%= f.text_field :description %>

						<%= f.label :year, "Ano" %>
						<%= f.text_field :year %>

						<%= f.label :director, "Diretor" %>
						<%= f.text_field :director %>

						<%= f.label :category, "Categoria" %>
						<%= f.text_field :category%>


						<a class="waves-effect waves-light btn">
							<%= f.submit "Criar Filme" 	%></a>
					<% end %>
					</div>
	</div>

EP3 /app/views/movies/show.html.erb
<head>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
 <div class="fixed-action-btn click-to-toggle" style="top: 55px;right:20;">
    <a class="waves-effect waves-light btn-large yellow darken-4">
      <i class="large material-icons">Explorar</i>
      <i class="large mdi-navigation-menu"></i>
    </a>
    <ul>
      <li><%= link_to "Ação", category_path(category: "Ação"), class: "waves-effect waves-light btn teal darken-4" %></li>
      <li><%= link_to "Animação", category_path(category: "Animação"), class: "waves-effect waves-light btn green" %></li>
      <li><%= link_to "Comédia", category_path(category: "Comédia"), class: "waves-effect waves-light btn yellow darken-1" %></li>
      <li><%= link_to "Drama", category_path(category: "Drama"), class: "waves-effect waves-light btn deep-blue lighten-4" %></li>
      <li><%= link_to "Documentário", category_path(category: "Documentário"), class: "waves-effect waves-light btn teal darken-2" %></li>
      <li><%= link_to "Ficção Científica", category_path(category: "Ficção Científica"), class: "waves-effect waves-light btn grey darken-2" %></li>
      <li><%= link_to "Romance", category_path(category: "Romance"), class: "waves-effect waves-light btn red" %></li>
    </ul>
    </div>

</head>
<center>

	<div class="parallax-container">
    <%=image_tag(@movie.image.url(:large))%>



    <div class="parallax"></div>
  </center>  

  	</div>
  	<div class="section white">
<center>


     <%if user_signed_in?%>
     botoes de avaliação

     <% end %>

</center>

   		<div class="row container">

      	<h2 class="header"><%= @movie.name%></br></h2>
      	  <div class="divider"></div>
      	  <div class="col s5">
  			<div class="section">
    		<h5>Categoria</h5>
    		<p><%= @movie.category%></br></p>
  			</div>

  			<div class="section">
    		<h5>Ano</h5>
    		<p><%= @movie.year%></br></p>
  			</div>

  			<div class="section">
    		<h5>Diretor</h5>
    		<p><%= @movie.director%></br></p>
  			</div>
      	
    	  </div>
    	  <div class="col s5">
    	  	<h5>Sinopse</h5>
    		<p><%= @movie.description%></br></p>
    	  </div>

		</div>
		<center>

    <%if user_signed_in?%>
      <%if current_user.role_admin?%>
     
                		 <div class="waves-effect waves-light btn z-depth-5 blue-grey lighten-4" style="font-color:#ffffff;">
                		 	<%= link_to 'Editar', edit_movie_path %>
                		 </div>

                		&nbsp;&nbsp;&nbsp;
                		 <a class="waves-effect waves-light btn z-depth-5">
                		 	<%= button_to "Excluir filme", movie_path, method: :delete %>
                		 </a>
        <% end %>        
		<% end%>    
		</center>
     
	</div>
  

EP3 /app/views/pages/home.html.erb
<head>
  <div class="fixed-action-btn click-to-toggle" style="top: 55px;right:20;">
    <a class="waves-effect waves-light btn-large yellow darken-4">
      <i class="large material-icons">Explorar</i>
      <i class="large mdi-navigation-menu"></i>
    </a>
    <ul>
      <li><%= link_to "Ação", category_path(category: "Ação"), class: "waves-effect waves-light btn teal darken-4" %></li>
      <li><%= link_to "Animação", category_path(category: "Animação"), class: "waves-effect waves-light btn green" %></li>
      <li><%= link_to "Comédia", category_path(category: "Comédia"), class: "waves-effect waves-light btn yellow darken-1" %></li>
      <li><%= link_to "Drama", category_path(category: "Drama"), class: "waves-effect waves-light btn deep-blue lighten-4" %></li>
      <li><%= link_to "Documentário", category_path(category: "Documentário"), class: "waves-effect waves-light btn teal darken-2" %></li>
      <li><%= link_to "Ficção Científica", category_path(category: "Ficção Científica"), class: "waves-effect waves-light btn grey darken-2" %></li>
      <li><%= link_to "Romance", category_path(category: "Romance"), class: "waves-effect waves-light btn red" %></li>
    </ul>
    </div>
  </head>
  <body>



  <head>
    <center>
        <div class="container" style="width=40%;">
         <%= form_tag(movies_path, :method => :get) do %>

          <%= text_field_tag 'search', '', placeholdder: 'Enter search ter...'%>
            
            <%= submit_tag "search" %>
            
          <% end %>
        </div>
    </center>
  </head>
  </body>

EP3 /app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>